### ISSUE TITLE
Active tab border "twitches" instead of appearing smoothly

### ISSUE THREAD

**Issue by web2style** [tleunen/react-mdl#30] opened 2015-09-08 07:24 UTC
Just have run tabs demo and found out this issue. Appears at least in chrome and firefox, didn't test in other browsers. Can you reproduce it?

**Comment by tleunen** [comment] 2015-09-09 20:01
What do you mean exactly? Providing an animated gif/video would help I think ;)

**Comment by web2style** [comment] 2015-09-09 20:35
Here is the video: https://www.dropbox.com/s/mrmxm64ibr4z7v3/20150909-233330.mkv?dl=0

**Comment by tleunen** [comment] 2015-09-09 23:07
Yeah I remember seeing this as well, but it's a upstream issue. On the getmdl website, you can also reproduce it.
They also said the animation was not right and I think they think about changing it to match what the material design describes.

**Comment by web2style** [comment] 2015-09-10 05:56
But there's no such issue at MDL website: http://www.getmdl.io/components/index.html#layout-section/tabs

**Comment by tleunen** [comment] 2015-09-10 12:09
I do have the same issue on my side, I opened an issue about it on the mdl repo a few weeks ago. They closed it because it was linked to another issue mentioning the animation is not correct.
See this https://github.com/google/material-design-lite/issues/1335

**Comment by tleunen** [comment] 2015-10-09 01:48
Upstream issue, see https://github.com/google/material-design-lite/issues/954

**Closed by tleunen** 2015-10-09 01:48 UTC
