### ISSUE TITLE
BUG: get error when using HeaderTabs component

### ISSUE THREAD

**Issue by Chun-Yang** [tleunen/react-mdl#265] opened 2016-03-23 02:46 UTC
First, Thanks for your awesome project!

Here is the bug:
When I use the HeaderTabs component and try to click one of the tab, I get the error:
```
TypeError: Cannot read property 'charAt' of null
```

It is in line 3575 of the material.js file
```
    tab.addEventListener('click', function (e) {
        if (tab.getAttribute('href').charAt(0) === '#') {  // <=== line 3575
            e.preventDefault();
            selectTab();
        }
    });
```
FYI, I copied the materiali.js file from your repo https://github.com/tleunen/react-mdl/blob/master/extra/material.js

After I comment this event listener, the bug disappeared.

Do you think it is a good idea to remove these lines? Or there are some other ways to fix this?

Again, thanks for your awesome project!

**Comment by tleunen** [comment] 2016-03-23 02:50
Duplicate of https://github.com/tleunen/react-mdl/issues/255
Should have been fixed in 1.5.2. What version are you using?

**Closed** 2016-03-23 03:05 UTC

**Comment by Chun-Yang** [comment] 2016-03-23 03:07
I am using version 1.5.2

**Comment by tleunen** [comment] 2016-03-23 03:09
hmm indeed the error is still thrown... Yes it's safe to remove it, it's not used anyway since 1.5.2 :)
Unfortunately, unless they change something in the base MDL lib, it's not something we can fix.

**Comment by raphaguasta** [comment] 2016-08-17 14:09
Hello guys! I'm using version 1.6.1, but the error still is thrown. Do you have any solution for this problem?
