### ISSUE TITLE
Tooltip clone element breaks event listeners

### ISSUE THREAD

**Issue by vurt007** [tleunen/react-mdl#210] opened 2016-02-09 13:54 UTC
Hi 
pretty new to react..
I've been trying to use the Tooltip to wrap an IconButton

`
function blah(){ alert('clicked');}
render() { return (
<Tooltip label="download"><IconButton name="download" onClick={blah} /></Tooltip>
)}`

What I've found is that when wrapped in a tooltip the onClick event no longer fires, when wrapped in the tooltip

**Comment by tleunen** [comment] 2016-02-09 14:32
Yes, this is related to https://github.com/tleunen/react-mdl/issues/65
Because of mobile, the click event is used to display the tooltip :s 
There's nothing we can do for now to fix this.

@faergeek Do you think it would be better to refactor the tooltip by using our own custom implementation instead? But we won't support mobile I guess :/

**Comment by faergeek** [comment] 2016-02-09 16:35
@tleunen I'm pretty sure that it's already fixed in mdl 1.1.0, so it's already fixed in master here.
@vurt007 Could you try to install this package from master branch and test?

**Comment by tleunen** [comment] 2016-02-09 16:35
Great news if it's fixed in 1.1.x.. I'll make some test tonight :)

**Comment by tleunen** [comment] 2016-02-10 02:35
Confirmed it's fixed in MDL 1.1.x, so it will be fixed in react-mdl 1.4.0. Closing it.
Good job on your fix @faergeek https://github.com/google/material-design-lite/commit/0e65b743a0d60cd186cb941c3f46361527fe376c

**Closed by tleunen** 2016-02-10 02:35 UTC

**Comment by vurt007** [comment] 2016-02-10 08:00
great, thanks ... I'll update

**Comment by faergeek** [comment] 2016-02-10 08:18
@tleunen Thanks :-)
